server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        # ===== security-service routes (Auth is Public) =====
        - id: security-service-auth
          uri: lb://security-service
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                secured: false

        # ===== quantity-measurement-app routes (Secured) =====
        - id: quantity-measurement-app
          uri: lb://quantity-measurement-app
          predicates:
            - Path=/api/v1/quantities/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                secured: true

# JWT secret (must be identical across all services)
__jwt__:
  secret: d3070215bf7c78ac7b7d85de0abf8ffeb164866576cf6b6eb1ac1c631d330ae5

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway