# ===== Spring Boot Application =====
spring.application.name=quantity-measurement-app


spring.datasource.url=jdbc:mysql://localhost:3306/quantitydb
spring.datasource.username=root
spring.datasource.password=mysql@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=d3070215bf7c78ac7b7d85de0abf8ffeb164866576cf6b6eb1ac1c631d330ae5
jwt.expiration=86400000


logging.level.org.springframework.web=DEBUG


# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23lizM8YKJPh5A2LEi
spring.security.oauth2.client.registration.github.client-secret=83a816e3d42f13f6914b62a39b380c3e1d364fcb

spring.security.oauth2.client.registration.github.scope=user:email